### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by RealStormi** [RealStormi/drunkobotsite#23]
- [ ] Support Invite isnt Working
- [ ] Making Image 150% big
- [ ] Make the Text on About & Privacy better
- [ ] Add the CSS to the About Page
- [ ] Home Button

**Comment by RealStormi** [comment]
Working on Mobile -> No Pictured Displayed

**Comment by RealStormi** [comment]
Support Invite Fixed

**Comment by RealStormi** [comment]
About Page now has CSS

**Comment by RealStormi** [comment]
10 PM Update:
- Updated the Privacy Page (still needs a Update)
- Need to Change the Clickable Link
- I hate the Design from the About Page lol

**Comment by RealStormi** [comment]
Almost 11 PM:
Privacy Page should be good now

**Comment by RealStormi** [comment]
Update:
 - Added Special Thanks
 - Changed the Link Text
 - Fixed Buttons
 - Fixed Error 404 Page
 - Added Back Button to the 404 Page

**Comment by RealStormi** [comment]
I added now a Changelog Page!

**Comment by RealStormi** [comment]
Added a Link Page
